import { Link } from "@mui/material";
import Head from "next/head";
import Exploration from "../src/components/Exploration/Exploration";
import Footer from "../src/components/Footer/Footer";
import Main from "../src/components/Main/Main";
import Navbar from "../src/components/Navbar/Navbar";
import News from "../src/components/News/News";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tabiyat.kg</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <main>
        <Navbar />
        {/* <Link href="/">
          <ArrowCircleUpIcon className={styles.up}></ArrowCircleUpIcon>
        </Link> */}
        <Main />
        <Exploration />
        <News />
        <Footer />
      </main>
    </div>
  );
}
